---
title: "MH"
format: html
editor: visual
---

```{r}

g <- function(x,mu=0,std=10){
  if (x>=0){
    return(2*dnorm(x,sd=std))
  }
  else{
    return(0)
  }
}

mh_demi_gauss <- function(lambda1,sigma0=10^6,std_k,N,theta0){
  # On utilise un kernel gaussien
  log_theta <- log(theta0)
  lambda2 = c(1:N)
  i <- 0
  nbr_total = 0
  while (i < N){
    epsilon <- rnorm(n=1,mean=0,sd= std_k)
    log_prop <- log_theta +epsilon
    prop <- exp(log_prop)
    theta <- exp(log_theta)
    numerateur <-log_prop + log(g(prop, std=sigma0))
    denominateur<- log_theta + log(g(theta, std=sigma0))
    alpha <-exp(numerateur-denominateur)
    u <- runif(n=1,0,1)
    nbr_total <- nbr_total+1
    if (u<=alpha){
      i <- i+1
      lambda2[i] <- (prop)+lambda1
      log_theta <- log_prop
    }
    
  }
  attr(lambda2, "taux_acc") <- i/nbr_total
  return(lambda2)
  
}
```

```{r}
y=mh_demi_gauss(0,sigma0=100,3,10000,5)
```

```{r}

```

```{r}
save(mh_demi_gauss, file = 'generateur_demi_gaussienne.RData')
```
